const allPapers = [
  {
    id: "shift1",
    title: "JEE Mains 2026 — 2 April (Shift 1)",
    subtitle: "Memory-Based Question Paper",
    conducted_by: "National Testing Agency (NTA)",
    duration: 180,
    totalMarks: 300,
    marking: { correct: 4, incorrect: -1, unanswered: 0 },
    sections: [
      {
        name: "Physics",
        icon: "⚛️",
        color: "#6C63FF",
        questions: [
          { id: "S1P1", type: "mcq", text: "The dimension of (1/2)ε₀E² is Mᵃ Lᵇ Tᶜ, then the value of a − 2b + c is:", options: ["1", "2", "3", "4"], answer: 0, topic: "Units & Dimensions" },
          { id: "S1P2", type: "mcq", text: "If angular position of a particle is given by θ = t⁴/4 + t². Find angular acceleration at t = 1s:", options: ["6 rad/s²", "5 rad/s²", "10 rad/s²", "6 rad/s²"], answer: 2, topic: "Rotational Motion" },
          { id: "S1P3", type: "mcq", text: "If r⃗ = 10t²î + 5t³ĵ and mass of object m = 0.1 kg, then at t = 1s:\n(A) momentum = 2î + 1.5ĵ\n(B) force = 2î + 3ĵ\n(C) Angular momentum = 5k̂\n(D) Torque = 20k̂\nWhich are correct?", options: ["A, B, C are correct", "A, C, D are correct", "A, C are correct", "A, B, C, D are correct"], answer: 2, topic: "Newton's Laws" },
          { id: "S1P4", type: "numerical", text: "If stress at x = ℓ/3 from bottom is W/A + (2/γ)(W/A), then find γ. (Refer to the figure showing a vertical bar subjected to load W).", answer: 3, topic: "Mechanical Properties" },
          { id: "S1P5", type: "numerical", text: "A particle is moving such that its velocity vector at coordinate (x, y, z) is v⃗ = −xî + 2yĵ − zk̂. Find magnitude of acceleration at (1, 1, 4).", answer: 5, topic: "Kinematics" },
          { id: "S1P6", type: "mcq", text: "Two spheres are connected with a conducting wire. Es1 and Es2 are electric fields at the surface of spheres at equilibrium. Find Es1/Es2.", options: ["4.5", "1.125", "2.25", "7.5"], answer: 2, topic: "Electrostatics" },
          { id: "S1P7", type: "mcq", text: "Wavelength used in single slit diffraction is 628 nm. Width of slit is 0.2 mm. Find the angular width of central maxima in degree.", options: ["0.36°", "0.38°", "0.45°", "0.40°"], answer: 0, topic: "Wave Optics" },
          { id: "S1P8", type: "mcq", text: "A wooden cubical block of relative density 0.4 is floating in water. Side of the cube is 10 cm. When a coin is placed on the block, it dips by 0.3 cm. Find the weight of the coin.", options: ["0.1 N", "0.2 N", "0.3 N", "0.4 N"], answer: 2, topic: "Fluid Mechanics" },
          { id: "S1P9", type: "mcq", text: "On a metal surface if light of wavelength λ falls, the stopping potential for emitted photoelectrons is 3V₀. If light of wavelength 2λ falls, the stopping potential is V₀. Find the threshold wavelength.", options: ["4λ", "3λ", "5λ", "2λ"], answer: 0, topic: "Photoelectric Effect" },
          { id: "S1P10", type: "numerical", text: "A container of initial volume 0.15 m³ is expanded adiabatically from pressure 8 bar to final pressure 1 bar. If initial temperature is 140K, find work done by the gas. (Cp = 3R, Cv = 2R)", answer: 60, topic: "Thermodynamics" },
          { id: "S1P11", type: "mcq", text: "Diagram shows a circuit consisting of some elements. The input and output of the circuit is shown. Choose the correct option that shows the component in box. (Zener diode has a breakdown potential of 5V).", options: ["X → diode → resistor → Y", "X → reverse diode → resistor → Y", "X → two diodes → Y", "X → opposite diodes → Y"], answer: 0, topic: "Semiconductor Electronics" },
          { id: "S1P12", type: "mcq", text: "Consider two arrangements of wires. Find out ratio of magnetic field at center of semi-circular part:", options: ["(2+π)/(1+π)", "(1+π)/(2+π)", "(2+π)/(2+π)", "(2+π)/(3+π)"], answer: 0, topic: "Magnetic Effects of Current" },
          { id: "S1P13", type: "mcq", text: "Object is placed at 40 cm from a spherical surface whose radius of curvature is 20 cm. Refractive index of medium is μ = 1.54. Find height of image formed.", options: ["2 cm", "4 cm", "0.96 cm", "1.96 cm"], answer: 2, topic: "Ray Optics" },
          { id: "S1P14", type: "mcq", text: "A satellite is revolving around a planet of mass 2M in orbit of radius R with time period T₁. Another satellite is revolving around a planet of mass 4M in orbit of radius 2R with time period T₂. Find T₁/T₂.", options: ["1/√2", "√2", "1/2", "1/(2√2)"], answer: 0, topic: "Gravitation" },
          { id: "S1P15", type: "numerical", text: "There is a parallel plate capacitor of capacitance C. If half of the space is filled with dielectric of dielectric constant k = 5 as in the figure, find the percentage increase in capacitance.", answer: 200, topic: "Capacitance" },
          { id: "S1P16", type: "mcq", text: "In Searle's experiment diameter of wire is measured with screw gauge of least count 0.001 cm and its value is 0.08 cm. Length of wire is 150 cm with least count 0.1 cm and elongation 0.5 cm with least count 0.001 cm. Weight suspended is 100 N. Find absolute error in Young's modulus if the value is written as N × 10⁹ N/m². Find N.", options: ["1.64", "1.65", "1.63", "1.66"], answer: 0, topic: "Experimental Physics" },
          { id: "S1P17", type: "numerical", text: "Thin symmetric prism of refractive index μ = 1.5. Find ratio of incident angle and minimum deviation.", answer: 3, topic: "Ray Optics" },
          { id: "S1P18", type: "mcq", text: "For diatomic gas, find the ratio Q : ΔU : W for isobaric process.", options: ["2 : 5 : 7", "2 : 3 : 5", "2 : 7 : 3", "7 : 5 : 2"], answer: 3, topic: "Thermodynamics" },
          { id: "S1P19", type: "mcq", text: "Net electric field at point A as shown in figure is at an angle of 60° with x-axis. Find P₂/P₁.", options: ["1/√3", "2√3", "√3", "√3/2"], answer: 2, topic: "Electrostatics" },
          { id: "S1P20", type: "mcq", text: "Angular momentum of the electron in a hydrogen atom is 3h/2π, then find the energy of the electron in that orbit:", options: ["-13.6 eV", "-3.4 eV", "-1.51 eV", "-0.85 eV"], answer: 2, topic: "Atoms" },
          { id: "S1P21", type: "numerical", text: "The equation of a plane progressive wave is given by y = 5cos π(200t − x/150), where x and y are in cm and t is in seconds. Find the wave velocity (in cm/s).", answer: 30000, topic: "Waves" },
          { id: "S1P22", type: "mcq", text: "Li²⁺ → Li³⁺ + e⁻. Energy required for this process. Given ionisation energy for ground state of hydrogen atom is 2.17 × 10⁻¹⁸ J.", options: ["19.53 × 10⁻¹⁸ J", "19.54 × 10⁻¹⁸ J", "19.56 × 10⁻¹⁸ J", "19.55 × 10⁻¹⁸ J"], answer: 0, topic: "Atoms" },
          { id: "S1P23", type: "mcq", text: "Electric field of electromagnetic wave is E = 800 sin(π(10⁸t + x/150)) V/m, where x is in cm and t in seconds. A charged particle is moving with speed 1.5 × 10⁶ m/s. Find the ratio of magnetic force to electric force on the charge particle.", options: ["10⁻²", "10⁻²", "2 × 10²", "2 × 10⁻²"], answer: 0, topic: "Electromagnetic Waves" },
          { id: "S1P24", type: "mcq", text: "A liquid drop having diameter 2 mm and surface tension 0.08 N/m. This drop splits into 512 identical small drops. Find change in surface energy.", options: ["4.034 × 10⁻⁶ J", "5 × 10⁻⁶ J", "7.034 × 10⁻⁶ J", "9.03 × 10⁻⁶ J"], answer: 2, topic: "Surface Tension" },
          { id: "S1P25", type: "mcq", text: "If power dissipated in a coil having total number of turns N, cross-section area A and radius of coil R when kept in a time varying magnetic field is P. Now if another coil having total number of turns 2N, cross-section area 2A and radius 3R is placed in the same time varying magnetic field, the power dissipated is αP. Find value of α.", options: ["108", "324", "216", "432"], answer: 0, topic: "Electromagnetic Induction" }
        ]
      },
      {
        name: "Chemistry",
        icon: "🧪",
        color: "#00C9A7",
        questions: [
          { id: "S1C1", type: "numerical", text: "For first order reaction, rate constant at 27°C and t° are 1.5 × 10³ and 4.5 × 10³ respectively. If activation energy of the reaction is 60 kJ/mol, then (R = 8.3 J mol⁻¹ K⁻¹, ln 3 = 1.1) Find temperature t (in °C).", answer: 54, topic: "Chemical Kinetics" },
          { id: "S1C2", type: "numerical", text: "One mole of an alkane on complete combustion required 8 moles of O₂, find out the sum of carbon and hydrogen atoms in one molecule of the alkane.", answer: 16, topic: "Hydrocarbons" },
          { id: "S1C3", type: "mcq", text: "Relation between t₁/₂ and t₁₀₀% for zero order and first order reaction respectively is:", options: ["t₁₀₀% = 2 × t₁/₂ : t₁₀₀% = 2 × t₁/₂", "t₁₀₀% = 2 × t₁/₂ : t₁₀₀% = t₁/₂", "t₁₀₀% = 2 × t₁/₂ : t₁₀₀% = ∞", "t₁₀₀% = ∞ : t₁₀₀% = 2 × t₁/₂"], answer: 2, topic: "Chemical Kinetics" },
          { id: "S1C4", type: "mcq", text: "18 g of steam reacted with iron to form Fe₃O₄, how much iron will be consumed?", options: ["21 gm", "42 gm", "84 gm", "10.5 gm"], answer: 1, topic: "Stoichiometry" },
          { id: "S1C5", type: "mcq", text: "Angular momentum of the electron in a hydrogen atom is 3h/2π, then find the total energy of the electron (in eV/atom).", options: ["-1.51", "-122.4", "-40.8", "-4.53"], answer: 0, topic: "Atomic Structure" },
          { id: "S1C6", type: "numerical", text: "For a reversible adiabatic process involving ideal gas, if initial pressure and volume are 8 bar and 0.15 m³ respectively, and final pressure is 1 bar. Calculate |work done| (in Kilojoule). [Cv = 2R, Cp = 3R]", answer: 60, topic: "Thermodynamics" },
          { id: "S1C7", type: "numerical", text: "For reaction A ⇋ B, ΔG° = 10⁵ − 35 log T. Find the transition temperature (in °C) of the above reaction at 1 bar.", answer: 727, topic: "Thermodynamics" },
          { id: "S1C8", type: "mcq", text: "Given Ksp(Ag₂C₂O₄) = 32X and Ksp(AgBr) = 4Y. Find the ratio of solubility of the given salts in pure water.", options: ["X¹ᐟ³ / √(2Y)", "2X¹ᐟ³ / √(2Y)", "2X¹ᐟ³ / √Y", "X¹ᐟ³ / √Y"], answer: 2, topic: "Ionic Equilibrium" },
          { id: "S1C9", type: "mcq", text: "19.5 gm FCH₂COOH is dissolved in 500 gm water due to which depression in freezing point is found to be 1°C. Calculate Ka of FCH₂COOH.\nGiven: ΔTf = 1°C, Mass of solute = 19.5 gm, Mass of solvent = 500 gm, Kf of water = 1.86 K kg/mole.", options: ["2.8 × 10⁻³", "2.8 × 10⁻²", "1.4 × 10⁻³", "5.6 × 10⁻³"], answer: 0, topic: "Colligative Properties" },
          { id: "S1C10", type: "mcq", text: "Consider the following reaction:\nFe(OH)₂ + 2e⁻ → Fe(s) + 2OH⁻(aq), E° = −0.88 V\nAgBr(s) + e⁻ → Ag(s) + Br⁻(aq), E° = 0.07 V\nSelect the correct statement.", options: ["E°cell = −0.95 V", "E°cell is an extensive property", "Fe is getting reduced", "Net cell reaction: Fe(s) + 2OH⁻(aq) + 2AgBr(s) → Fe(OH)₂(s) + 2Ag(s) + 2Br⁻(aq)"], answer: 3, topic: "Electrochemistry" },
          { id: "S1C11", type: "mcq", text: "Match the column and select the correct option:\n(Column matching question — refer to original paper for table data)", options: ["(i)→R, (ii)→Q, (iii)→S, (iv)→P", "(i)→Q, (ii)→R, (iii)→S, (iv)→P", "(i)→R, (ii)→Q, (iii)→P, (iv)→S", "(i)→S, (ii)→Q, (iii)→R, (iv)→P"], answer: 0, topic: "General Chemistry" },
          { id: "S1C12", type: "numerical", text: "Organic compound C₅H₁₀ does not give Baeyer's reagent test. Calculate the total number of structural monobromo isomers when reacted with Br₂/hν.", answer: 4, topic: "Organic Chemistry" },
          { id: "S1C13", type: "mcq", text: "Match correctly with the reagents given in Column-I with organic compounds given in Column-II.", options: ["(i)-Q, (ii)-R, (iii)-P, (iv)-S", "(i)-P, (ii)-Q, (iii)-R, (iv)-S", "(i)-R, (ii)-S, (iii)-Q, (iv)-P", "(i)-S, (ii)-R, (iii)-Q, (iv)-P"], answer: 0, topic: "Organic Chemistry" },
          { id: "S1C14", type: "mcq", text: "Write the correct order of rate of reaction of following compounds with PhN₂Cl.", options: ["P > Q > R", "P > R > Q", "Q > P > R", "R > P > Q"], answer: 0, topic: "Organic Chemistry" },
          { id: "S1C15", type: "mcq", text: "Most preferred site for electrophilic substitution in the given example?", options: ["Predominantly at U", "S and R", "Predominantly at R", "R and S"], answer: 2, topic: "Organic Chemistry" },
          { id: "S1C16", type: "mcq", text: "Which of the following order is correct for priority of functional group in IUPAC nomenclature?", options: ["−CHO > −COOR > −CO > −CN > −NH₂", "−CONH₂ > −CN > −CHO > −CO > −NH₂", "−CONH₂ > −COOR > −CN > −CHO > −CO", "−COOR > −CN > −CONH₂ > −CHO > −CO"], answer: 2, topic: "IUPAC Nomenclature" },
          { id: "S1C17", type: "mcq", text: "Statement-1: Benzyl chloride reacts faster than ethyl chloride towards SN1.\nStatement-2: Positive charge on ethyl will be unstable.", options: ["Statement-I and Statement-II both are correct", "Statement-I and Statement-II both are incorrect", "Statement-I correct but Statement-II is incorrect", "Statement-I incorrect but Statement-II is correct"], answer: 0, topic: "Organic Chemistry" },
          { id: "S1C18", type: "mcq", text: "Statement-I: 1,2,3-trihydroxy propane can be separated from water by using simple distillation.\nStatement-II: Azeotropic mixture cannot be separated by using fractional distillation.", options: ["Statement-I and Statement-II both are correct", "Statement-I and Statement-II both are incorrect", "Statement-I correct but Statement-II is incorrect", "Statement-I incorrect but Statement-II is correct"], answer: 3, topic: "Solutions" },
          { id: "S1C19", type: "mcq", text: "Statement-I: The correct increasing order of bond length among the following is O₂⁺ < O₂ < O₂⁻ < O₂²⁻\nStatement-II: The correct order of number of unpaired electrons is O₂²⁻ < O₂ < O₂⁺ < O₂⁻", options: ["Both Statement-I and Statement-II are correct", "Statement-I is correct and Statement-II is incorrect", "Statement-II is correct and Statement-I is incorrect", "Both Statement-I and Statement-II are incorrect"], answer: 1, topic: "Chemical Bonding" },
          { id: "S1C20", type: "mcq", text: "Statement-I: The correct order of ionization energy is Na > Mg > Al > Ar\nStatement-II: Among the following elements Sc, Ca, and Mg, Ca has highest 3rd ionization energy.", options: ["Both Statement-I and Statement-II are correct", "Statement-I is correct but Statement-II is incorrect", "Statement-I is incorrect but Statement-II is correct", "Both Statement-I and Statement-II are incorrect"], answer: 2, topic: "Periodic Properties" },
          { id: "S1C21", type: "mcq", text: "Cation of salt A when treated in flame gives apple green colour. When salt A is heated with Chromate solution it gives yellow precipitate & when salt is heated with conc. HNO₃ & Ammonium molybdate it gives canary yellow ppt. Salt A contains:", options: ["Ba²⁺ and PO₄³⁻", "Ca²⁺ and SO₄²⁻", "Ba²⁺ and SO₄²⁻", "Sr²⁺ and PO₄³⁻"], answer: 0, topic: "Salt Analysis" },
          { id: "S1C22", type: "numerical", text: "5.33 gram of CrCl₃·6H₂O (1:3 electrolyte) is passed through cation exchanger. The resulting solution is then treated with an excess of AgNO₃, leading to formation of 8.61 gram of precipitate. Calculate:\n(Number of moles of complex reacted / Number of moles of AgCl precipitated) × 100", answer: 33, topic: "Coordination Compounds" },
          { id: "S1C23", type: "mcq", text: "Find the correct match.\n(Column matching question — refer to original paper for table data)", options: ["(i)→P; (ii)→Q; (iii)→S; (iv)→R", "(i)→S; (ii)→Q; (iii)→P; (iv)→R", "(i)→R; (ii)→P; (iii)→Q; (iv)→S", "(i)→P; (ii)→R; (iii)→Q; (iv)→S"], answer: 0, topic: "General Chemistry" }
        ]
      },
      {
        name: "Mathematics",
        icon: "📐",
        color: "#FF6B6B",
        questions: [
          { id: "S1M1", type: "mcq", text: "If y = f(x) is the solution of the differential equation (1 + sin x)(dy/dx) + cos x = 0, such that f(0) = 0, then f(π/2) is:", options: ["ln 2", "−ln 2", "ln 3", "ln 4"], answer: 0, topic: "Differential Equations" },
          { id: "S1M2", type: "mcq", text: "The value of ∫₀³ [eˣ + e⁻ˣ] dx is equal to (where [·] denotes greatest integer function):", options: ["e³ + e² − e⁻² − e⁻³/2", "e³ − e² − e⁻² + e⁻³/2", "e³ + e² − e⁻² − e⁻³", "e³ − e² − e⁻² + e⁻³"], answer: 3, topic: "Definite Integration" },
          { id: "S1M3", type: "mcq", text: "Number of seven-digit numbers which can be formed by using all the digits 1, 2, 3, 4, 5 with at least one digit repeated is:", options: ["16200", "15600", "16800", "14800"], answer: 2, topic: "Permutations & Combinations" },
          { id: "S1M4", type: "mcq", text: "The range of f(x) = sin⁻¹(1/(x² − 2x + 2)) is:", options: ["(0, π/2)", "[0, π/2]", "(0, π/2]", "[0, π/2)"], answer: 2, topic: "Inverse Trigonometric Functions" },
          { id: "S1M5", type: "mcq", text: "Let x ∈ [−π, π] & S = {x : sin x(sin x + cos x) = a, a ∈ ℤ}, then number of elements in set S is equal to:", options: ["5", "10", "9", "4"], answer: 2, topic: "Trigonometry" },
          { id: "S1M6", type: "mcq", text: "A circle meets coordinate axes at 3 points and cuts equal intercepts. If it cuts a chord of length √14 unit on x + y = 1, then square of its radius is (centre lies in first quadrant):", options: ["2", "4", "8", "16"], answer: 2, topic: "Circles" },
          { id: "S1M7", type: "mcq", text: "Let |a⃗| = 2, |b⃗| = 3, then maximum value of 3|3a⃗ + 2b⃗| + 4|3a⃗ − 2b⃗| is:", options: ["50", "60", "70", "80"], answer: 1, topic: "Vectors" },
          { id: "S1M8", type: "mcq", text: "If probability that ax² + 2√(2b)x + c > 0 ∀x ∈ ℝ where a, b, c ∈ {1, 2, 3, 4} is m/n where m & n are coprime then (m + n) is:", options: ["81", "18", "78", "17"], answer: 3, topic: "Probability" },
          { id: "S1M9", type: "mcq", text: "Consider f(x) = |sin x / x|, x ≠ 0 and f(0) = 1. Number of critical points of f(x) in the interval (−2π, 2π) is:", options: ["3", "5", "7", "1"], answer: 2, topic: "Application of Derivatives" },
          { id: "S1M10", type: "mcq", text: "If eccentricity of an ellipse x²/a² + y²/b² = 1 which passes through the point (3, 4) is √5/3, then length of latus rectum of ellipse is:", options: ["4√5/3", "8√5/3", "4√7/3", "8√7/3"], answer: 1, topic: "Ellipse" },
          { id: "S1M11", type: "mcq", text: "Foot of perpendicular from origin on a line passing through (1, 1, 1) having direction ratios ⟨2, 3, 4⟩, is:", options: ["(11/29, 2/29, 7/29)", "(11/29, −2/29, −7/29)", "(11/29, 2/29, −7/29)", "(−11/29, 2/29, −7/29)"], answer: 0, topic: "3D Geometry" },
          { id: "S1M12", type: "mcq", text: "α, α+2 ∈ ℤ and n ∈ ℕ, where α, α+2 are roots of equation x(x+2) + (x+1)(x+3) + ⋯ + (x+n−1)(x+n+1) = 4n, then α + n =", options: ["0", "1", "2", "3"], answer: 1, topic: "Quadratic Equations" },
          { id: "S1M13", type: "mcq", text: "Let K = sin(π/18) sin(5π/18) sin(7π/18), then the value of sin(10Kπ/3) is:", options: ["(√3 − 1)/(2√2)", "(√3 + 1)/(2√2)", "(√3 + 1)/4", "(√3 − 1)/4"], answer: 0, topic: "Trigonometry" },
          { id: "S1M14", type: "mcq", text: "Value of definite integral I = ∫₀^(2√3) log₂(x² + 4) dx + ∫₂⁴ √(x² − 4) dx", options: ["2√3", "4√3", "6√3", "8√3"], answer: 0, topic: "Definite Integration" },
          { id: "S1M15", type: "numerical", text: "If Σₖ₌₁ⁿ aₖ = 6n³, then evaluate Σₖ₌₁⁶ ((aₖ₊₁ − aₖ)/36)²", answer: 91, topic: "Sequences & Series" },
          { id: "S1M16", type: "numerical", text: "If lim(x→2) sin(x³ − 5x² + ax + b) / ((√(x−1) − 1) · ln(x−1)) = m (exists finitely) then find the value of a + b + m.", answer: 8, topic: "Limits" },
          { id: "S1M17", type: "numerical", text: "A line through (1, 1, 1) and perpendicular to both î + 2ĵ + 2k̂ and 2î + 2ĵ + k̂, let (a, b, c) be foot of perpendicular from origin then 34(a + b + c) is:", answer: 34, topic: "3D Geometry" },
          { id: "S1M18", type: "numerical", text: "If ³⁶Cᵣ₊₁ / ³⁶Cᵣ = 6 · ³⁵Cᵣ / (k² − 3), then number of ordered pairs (r, k), where r, k ∈ ℤ is:", answer: 4, topic: "Binomial Theorem" },
          { id: "S1M19", type: "numerical", text: "Let mid-points of sides of △ be (5/2, 3), (5/2, 7) and (4, 5). If the in-centre is (h, k), then the value of 3h + k is:", answer: 17, topic: "Coordinate Geometry" },
          { id: "S1M20", type: "numerical", text: "If domain of f(x) = log((2x − 5)/(x² − 4)) is (a, b) ∪ (c, ∞), then the value of a + b + c is:", answer: 4, topic: "Functions" },
          { id: "S1M21", type: "numerical", text: "Consider two APs S₁ and S₂, such that S₁: First term = 1, Common difference = 5, no. of terms = 101; S₂: First term = 9, Common difference = 7, no. of terms = 71. Find the number of common terms in both APs.", answer: 3, topic: "Sequences & Series" },
          { id: "S1M22", type: "numerical", text: "If 50[2x/(1+3i) + y/(1−2i)] = 31 + 17i where x, y ∈ ℝ and i = √(−1), then the value of 10(x + 3y) is:", answer: 41, topic: "Complex Numbers" }
        ]
      }
    ]
  },
  {
    id: "shift2",
    title: "JEE Mains 2026 — 2 April (Shift 2)",
    subtitle: "Memory-Based Question Paper",
    conducted_by: "National Testing Agency (NTA)",
    duration: 180,
    totalMarks: 300,
    marking: { correct: 4, incorrect: -1, unanswered: 0 },
    sections: [
      {
        name: "Physics",
        icon: "⚛️",
        color: "#6C63FF",
        questions: [
          { id: "S2P1", type: "mcq", text: "In an equilateral prism the path of a ray is shown in the figure. The angle of incidence is 30° and the ray undergoes minimum deviation. Determine the refractive index of the prism.", options: ["1.71", "1.52", "1.39", "1.84"], answer: 0, topic: "Ray Optics" },
          { id: "S2P2", type: "mcq", text: "What is the equivalent gate for the following digital circuit? (Two NAND gates connected so that both inputs of the second NAND gate are tied to the output of the first NAND gate)", options: ["AND gate", "OR gate", "NOT gate", "NOR gate"], answer: 2, topic: "Digital Electronics" },
          { id: "S2P3", type: "mcq", text: "A soap bubble of radius r = 1 mm is rising in a liquid of density ρ = 2000 kg/m³. At the instant the bubble is rising upward with constant velocity v = 1/2 cm/s. Find the coefficient of viscosity (η).", options: ["2/9 N·s/m²", "4/9 N·s/m²", "2/3 N·s/m²", "8/9 N·s/m²"], answer: 1, topic: "Viscosity" },
          { id: "S2P4", type: "mcq", text: "Dimensions of G (Universal gravitational constant) in terms of h (Planck's constant), m (mass), t (time) and L (length) will be:", options: ["h⁻¹ L m⁻² t", "h L⁻¹ m² t", "h L m⁻² t⁻¹", "h⁻¹ L⁻¹ m² t⁻¹"], answer: 2, topic: "Units & Dimensions" },
          { id: "S2P5", type: "mcq", text: "Two charged spheres of radii R₁ = 2 cm and R₂ = 4 cm are connected by a long conducting wire. The ratio of electric fields at their surfaces E₁ : E₂ is:", options: ["1 : 2", "2 : 1", "1 : 4", "4 : 1"], answer: 1, topic: "Electrostatics" },
          { id: "S2P6", type: "mcq", text: "A particle of mass m is projected with velocity v₀ at angle θ with horizontal. At the highest point, its angular momentum about the point of projection is:", options: ["mv₀² sin2θ / 2g", "mv₀³ sin²θ cosθ / 2g", "mv₀³ cos²θ sinθ / g", "mv₀³ sinθ cos²θ / 2g"], answer: 3, topic: "Rotational Motion" },
          { id: "S2P7", type: "mcq", text: "A Zener diode has a breakdown voltage of 6V. It is connected in a circuit with a series resistance of 500 Ω and input voltage of 10V. The current through the Zener is:", options: ["2 mA", "4 mA", "6 mA", "8 mA"], answer: 3, topic: "Semiconductor Electronics" },
          { id: "S2P8", type: "mcq", text: "The electric potential at any point on the axis of a uniformly charged ring of charge Q and radius R at distance x from centre is:", options: ["kQ / R", "kQ / √(R² + x²)", "kQx / (R² + x²)^(3/2)", "kQ / x"], answer: 1, topic: "Electrostatics" },
          { id: "S2P9", type: "mcq", text: "A conducting rod of length L moves with velocity v perpendicular to a magnetic field B. If the rod has resistance R, the current induced is:", options: ["BLv / R", "BL²v / R", "Bv / LR", "B²L²v / R"], answer: 0, topic: "Electromagnetic Induction" },
          { id: "S2P10", type: "mcq", text: "In an LC oscillation circuit, the charge on capacitor varies as q = q₀ cos(ωt). The energy stored in the inductor at time t is:", options: ["q₀²ω² sin²(ωt) / 2L", "Lq₀²ω² sin²(ωt) / 2", "q₀² sin²(ωt) / 2C", "q₀²ω² sin²(ωt) L / 2"], answer: 1, topic: "Electromagnetic Oscillations" },
          { id: "S2P11", type: "mcq", text: "For a hydrogen atom, the wavelength of the photon emitted when an electron transitions from n = 4 to n = 2 is closest to:", options: ["486 nm", "656 nm", "434 nm", "410 nm"], answer: 0, topic: "Atoms" },
          { id: "S2P12", type: "mcq", text: "Two blocks of masses 3 kg and 5 kg are connected by a spring of spring constant k = 100 N/m on a frictionless surface. If the 3 kg block is displaced by 4 cm from equilibrium and released, the time period of oscillation is:", options: ["π/5 s", "2π/5 s", "π√2/5 s", "3π/5 s"], answer: 0, topic: "Simple Harmonic Motion" },
          { id: "S2P13", type: "mcq", text: "A gas expands adiabatically from (P₁, V₁) to (P₂, V₂). Select the correct relation:", options: ["P₁V₁ = P₂V₂", "P₁V₁^γ = P₂V₂^γ", "T₁V₁^(γ−1) = T₂V₂^(γ−1)", "Both B and C are correct"], answer: 3, topic: "Thermodynamics" },
          { id: "S2P14", type: "mcq", text: "An observer moving towards a stationary source of frequency 200 Hz with velocity 34 m/s observes frequency f. If speed of sound is 340 m/s, then f is:", options: ["180 Hz", "220 Hz", "185 Hz", "210 Hz"], answer: 1, topic: "Waves" },
          { id: "S2P15", type: "mcq", text: "In Young's double slit experiment, the fringe width is β₀ when the entire setup is in air. When the setup is immersed in a liquid of refractive index μ = 1.5, the new fringe width is:", options: ["1.5 β₀", "β₀/1.5", "β₀/√1.5", "β₀√1.5"], answer: 1, topic: "Wave Optics" },
          { id: "S2P16", type: "mcq", text: "A parallel plate capacitor has plates of area A separated by distance d. It is filled with two dielectric slabs of thickness d/2 each and dielectric constants k₁ = 2 and k₂ = 3. The effective capacitance is:", options: ["5ε₀A/2d", "12ε₀A/5d", "6ε₀A/5d", "5ε₀A/d"], answer: 1, topic: "Capacitance" },
          { id: "S2P17", type: "mcq", text: "A current-carrying wire is bent into a circular loop of radius R. The magnetic field at the centre of the loop due to current I is B. Now the same wire is bent into a coil of 4 turns. The magnetic field at the centre of the coil is:", options: ["4B", "8B", "16B", "2B"], answer: 2, topic: "Magnetic Effects of Current" },
          { id: "S2P18", type: "mcq", text: "A satellite orbits Earth at height h = R (R is radius of Earth). The orbital speed of the satellite is (g = acceleration due to gravity on surface):", options: ["√(gR)", "√(gR/2)", "√(2gR)", "√(gR/4)"], answer: 1, topic: "Gravitation" },
          { id: "S2P19", type: "mcq", text: "A metal surface is illuminated by photons of energy 5.0 eV. The work function of the metal is 3.5 eV. The stopping potential is:", options: ["1.0 V", "1.5 V", "3.5 V", "5.0 V"], answer: 1, topic: "Photoelectric Effect" },
          { id: "S2P20", type: "mcq", text: "In a meter bridge, the null point is found at 40 cm from one end when a resistance of 20 Ω is connected in one gap. The unknown resistance in the other gap is:", options: ["13.3 Ω", "30 Ω", "15 Ω", "10 Ω"], answer: 1, topic: "Current Electricity" },
          { id: "S2P21", type: "numerical", text: "A uniform rod of mass 2 kg and length 1 m is hinged at one end and held horizontally. When released, the angular velocity of the rod when it becomes vertical is (g = 10 m/s²): _____ rad/s (round to nearest integer).", answer: 5, topic: "Rotational Motion" },
          { id: "S2P22", type: "numerical", text: "The ratio of the de Broglie wavelengths of an electron accelerated through 100 V and a proton accelerated through 400 V is (mass of proton = 1836 × mass of electron). The value is approximately _____ (integer).", answer: 43, topic: "Dual Nature of Matter" },
          { id: "S2P23", type: "numerical", text: "In an RLC series circuit, R = 10 Ω, L = 0.1 H, C = 1000 μF. The resonant frequency is _____ Hz (use π² ≈ 10, give integer answer).", answer: 5, topic: "Alternating Current" },
          { id: "S2P24", type: "numerical", text: "A ball is dropped from a building of height 80 m. Simultaneously, another ball is thrown upward with velocity 20 m/s from the ground. They meet after _____ seconds. (g = 10 m/s²)", answer: 4, topic: "Kinematics" },
          { id: "S2P25", type: "numerical", text: "Three identical resistors each of resistance R = 12 Ω are connected in a triangular loop. The effective resistance between two adjacent vertices is _____ Ω.", answer: 8, topic: "Current Electricity" }
        ]
      },
      {
        name: "Chemistry",
        icon: "🧪",
        color: "#00C9A7",
        questions: [
          { id: "S2C1", type: "mcq", text: "Predict expression for $\\alpha$ in terms of $K_{eq}$ and concentration $C$:\n$$A_2B_3(aq) \\rightleftharpoons 2A^{3+}(aq) + 3B^{2-}(aq)$$", options: ["$(K_{eq} / 108C^4)^{1/5}$", "$(K_{eq} / 5C^4)^{1/5}$", "$(4K_{eq} / 5C^4)^{1/5}$", "$(9K_{eq} / 5C^4)^{1/5}$"], answer: 0, topic: "Ionic Equilibrium" },
          { id: "S2C2", type: "mcq", text: "Which of the following is most basic?", options: ["Tl₂O₃", "Tl₂O", "Cr₂O₃", "B₂O₃"], answer: 1, topic: "Periodic Properties" },
          { id: "S2C3", type: "mcq", text: "Arrange the following complexes in increasing order of CFSE (Δo):\n(a) [Co(H₂O)₆]²⁺\n(b) [Co(H₂O)₆]³⁺\n(c) [Co(en)₃]³⁺", options: ["c > a > b", "c > b > a", "a > b > c", "b > a > c"], answer: 2, topic: "Coordination Compounds" },
          { id: "S2C4", type: "mcq", text: "Consider the reaction given below:\nA gives positive Fehling's test. Choose the correct relation between molar masses.", options: ["Molar weight of A and molar weight of B are same", "Molar weight of A is greater than molar weight of B", "Molar weight of B is greater than molar weight of A", "None of these"], answer: 2, topic: "Organic Chemistry" },
          { id: "S2C5", type: "mcq", text: "Match List I with List II:\nI) Ethanol → P) Neutral FeCl₃\nII) Phenol → Q) Cerric ammonium nitrate\nIII) Ethanoic Acid → R) Schiff reagent\nIV) Acetaldehyde → S) NaHCO₃", options: ["I-P, II-Q, III-R, IV-S", "I-Q, II-S, III-P, IV-R", "I-P, II-Q, III-S, IV-R", "I-P, II-Q, III-S, IV-S"], answer: 2, topic: "Organic Chemistry" },
          { id: "S2C6", type: "mcq", text: "Products of ozonolysis of benzene followed by reductive workup are:", options: ["Phenol, Formaldehyde", "Benzaldehyde, Acetone", "Phenol, Acetone", "Only Glyoxal (OHC-CHO)"], answer: 3, topic: "Organic Chemistry" },
          { id: "S2C7", type: "mcq", text: "One mole of alkane reacts with 8 moles of O₂. The molecular formula of alkane is:", options: ["C₅H₁₂", "C₃H₁₂", "C₇H₁₄", "C₃H₈"], answer: 0, topic: "Hydrocarbons" },
          { id: "S2C8", type: "mcq", text: "The correct order of first ionization energy is:", options: ["Na < Mg < Al < Si", "Na < Al < Mg < Si", "Na < Mg < Si < Al", "Al < Na < Mg < Si"], answer: 1, topic: "Periodic Properties" },
          { id: "S2C9", type: "mcq", text: "Which one of the following is NOT a colligative property?", options: ["Osmotic pressure", "Elevation in boiling point", "Optical rotation", "Depression in freezing point"], answer: 2, topic: "Solutions" },
          { id: "S2C10", type: "mcq", text: "The product of Hoffmann Bromamide reaction of benzamide (C₆H₅CONH₂) with Br₂/KOH is:", options: ["Aniline", "Benzyl amine", "Phenyl isocyanate", "Nitrobenzene"], answer: 0, topic: "Amines" },
          { id: "S2C11", type: "mcq", text: "In the reaction: CH₃CHO + HCN → Product (A), which then undergoes hydrolysis to give:", options: ["Lactic acid", "Acetic acid", "Glycolic acid", "Pyruvic acid"], answer: 0, topic: "Aldehydes & Ketones" },
          { id: "S2C12", type: "mcq", text: "Among the following, the incorrect statement about the extraction of aluminium by Hall-Heroult process is:", options: ["Cryolite (Na₃AlF₆) is used as solvent", "The cathode is made of graphite", "Aluminium is deposited at anode", "Oxygen is liberated at anode"], answer: 2, topic: "Metallurgy" },
          { id: "S2C13", type: "mcq", text: "The IUPAC name of the compound: CH₃−CH(OH)−CH₂−COOH is:", options: ["3-hydroxybutanoic acid", "2-methylmalonaldehyde", "Beta-hydroxybutyric acid", "3-methylpropanoic acid"], answer: 0, topic: "IUPAC Nomenclature" },
          { id: "S2C14", type: "mcq", text: "Which of the following pairs shows maximum covalent character in their bond?", options: ["NaCl and KCl", "BeCl₂ and MgCl₂", "AlCl₃ and GaCl₃", "CsCl and RbCl"], answer: 1, topic: "Chemical Bonding" },
          { id: "S2C15", type: "mcq", text: "Statement I: XeF₄ has two lone pairs and is square planar.\nStatement II: The lone pairs of XeF₄ are at equatorial positions and bond pairs at axial.", options: ["Both Statement I and II are correct", "Statement I is correct, Statement II is incorrect", "Statement I is incorrect, Statement II is correct", "Both Statement I and II are incorrect"], answer: 1, topic: "Chemical Bonding" },
          { id: "S2C16", type: "mcq", text: "Among HF, HCl, HBr and HI, which has the lowest boiling point?", options: ["HF", "HCl", "HBr", "HI"], answer: 1, topic: "Hydrogen Halides" },
          { id: "S2C17", type: "mcq", text: "The Nernst equation for cell potential is E = E° − (RT/nF) ln Q. At 25°C, for a 2-electron reaction with E° = 1.10 V and Q = 100, the cell potential E is:", options: ["1.04 V", "1.16 V", "0.98 V", "1.10 V"], answer: 0, topic: "Electrochemistry" },
          { id: "S2C18", type: "mcq", text: "For the reaction N₂ + 3H₂ ⇌ 2NH₃, if Kc = 6 × 10⁻² at 500°C, which statement is correct?", options: ["Products are favoured at equilibrium", "Reactants are favoured at equilibrium", "Kp = Kc at this temperature", "Both Kp and Kc are dimensionless"], answer: 1, topic: "Chemical Equilibrium" },
          { id: "S2C19", type: "mcq", text: "The half-life of a first-order reaction is 10 minutes. The time required for 75% completion of the reaction is:", options: ["20 min", "15 min", "30 min", "25 min"], answer: 0, topic: "Chemical Kinetics" },
          { id: "S2C20", type: "mcq", text: "Which reagent is used to distinguish between primary, secondary and tertiary amines? (Hinsberg's test)", options: ["Benzenesulfonyl chloride", "Dil. HCl", "CHCl₃/KOH (Carbylamine test)", "NaNO₂/HCl"], answer: 0, topic: "Amines" },
          { id: "S2C21", type: "numerical", text: "The van't Hoff factor 'i' for 0.1 M K₃[Fe(CN)₆] which is 60% dissociated is _____. (Give answer × 10, i.e., if i = 2.8, write 28)", answer: 28, topic: "Solutions" },
          { id: "S2C22", type: "numerical", text: "At STP, 5.6 L of a gas X (molar mass 28 g/mol) weighs _____ g.", answer: 7, topic: "Mole Concept" },
          { id: "S2C23", type: "numerical", text: "For a reaction A → B + C, ΔH° = −100 kJ/mol. If activation energy Ea(forward) = 150 kJ/mol, then activation energy for the reverse reaction (in kJ/mol) is _____.", answer: 250, topic: "Chemical Kinetics" },
          { id: "S2C24", type: "numerical", text: "In electrolysis of CuSO₄ solution, 0.5 Faraday of charge is passed. The mass of copper deposited at cathode (atomic mass of Cu = 64 g/mol) is _____ g.", answer: 16, topic: "Electrochemistry" },
          { id: "S2C25", type: "numerical", text: "Molecular weight of a substance is 180 g/mol. 36 g of this substance is dissolved in 100 g of water. The molality of the solution is _____.", answer: 2, topic: "Solutions" }
        ]
      },
      {
        name: "Mathematics",
        icon: "📐",
        color: "#FF6B6B",
        questions: [
          { id: "S2M1", type: "mcq", text: "Sum of $\\frac{1^3}{1} + \\frac{1^3+2^3}{1+3} + \\frac{1^3+2^3+3^3}{1+3+5} + \\dots$ up to 8 terms is:", options: ["71", "70", "73", "72"], answer: 3, topic: "Sequences & Series" },
          { id: "S2M2", type: "mcq", text: "The value of $\\int_{0}^{2\\pi} (\\sin^4 x + \\cos^4 x) dx$ is equal to:", options: ["$3\\pi/2$", "$3\\pi/4$", "$3\\pi/8$", "$3\\pi$"], answer: 0, topic: "Definite Integration" },
          { id: "S2M3", type: "mcq", text: "If $\\alpha$ and $\\beta$ are the roots of $x^2 + px + q = 0$, then the equation whose roots are $\\alpha^2$ and $\\beta^2$ is:", options: ["$x^2 - (p^2 - 2q)x + q^2 = 0$", "$x^2 + (p^2 - 2q)x + q^2 = 0$", "$x^2 - (p^2 + 2q)x + q^2 = 0$", "$x^2 + (p^2 + 2q)x + q = 0$"], answer: 0, topic: "Quadratic Equations" },
          { id: "S2M4", type: "mcq", text: "The number of ways of arranging the letters of 'ARRANGE' such that the two R's are never together is:", options: ["360", "900", "1260", "840"], answer: 1, topic: "Permutations & Combinations" },
          { id: "S2M5", type: "mcq", text: "The equation of the tangent to the parabola y² = 4x at the point (1, 2) is:", options: ["x − y + 1 = 0", "x + y − 3 = 0", "x − y − 1 = 0", "y = x + 1"], answer: 0, topic: "Parabola" },
          { id: "S2M6", type: "mcq", text: "$\\lim_{x \\to 0} \\frac{\\sin(3x) + \\sin(5x)}{x}$ is equal to:", options: ["0", "4", "8", "3"], answer: 2, topic: "Limits" },
          { id: "S2M7", type: "mcq", text: "The value of sin 10° · sin 50° · sin 70° is:", options: ["1/8", "√3/8", "1/4", "√3/4"], answer: 0, topic: "Trigonometry" },
          { id: "S2M8", type: "mcq", text: "If A = [1  2; 3  4], then det(A² − 5A) =", options: ["2", "−2", "−4", "4"], answer: 1, topic: "Matrices & Determinants" },
          { id: "S2M9", type: "mcq", text: "The area enclosed between the parabola y = x² and the line y = x + 2 is:", options: ["7/2", "9/2", "11/2", "5/2"], answer: 1, topic: "Area Under Curves" },
          { id: "S2M10", type: "mcq", text: "A die is rolled twice. The probability that the sum of outcomes is a prime number is:", options: ["5/12", "5/9", "7/18", "13/36"], answer: 2, topic: "Probability" },
          { id: "S2M11", type: "mcq", text: "The general solution of the differential equation dy/dx = (x + y + 1)/(x + y − 1) is:", options: ["2(y − x) + ln(x + y) = C", "x + y − ln|x + y| = C", "y − x − ln|x + y| = C", "2x + 2ln|x + y| = C"], answer: 1, topic: "Differential Equations" },
          { id: "S2M12", type: "mcq", text: "The distance of the point (2, 3, 4) from the plane 3x − 6y + 2z = 11 is:", options: ["3/7", "11/7", "13/7", "6/7"], answer: 0, topic: "3D Geometry" },
          { id: "S2M13", type: "mcq", text: "If vectors a⃗ = î + 2ĵ + 3k̂ and b⃗ = 2î − ĵ + k̂, then a⃗ × b⃗ equals:", options: ["5î + 5ĵ − 5k̂", "5î − 5ĵ + 5k̂", "−5î + 5ĵ + 5k̂", "5î + 5ĵ + 5k̂"], answer: 0, topic: "Vectors" },
          { id: "S2M14", type: "mcq", text: "The number of solutions of $|z|^2 + 2(z + \\bar{z}) = 8$ where $z$ is a complex number is:", options: ["1", "2", "4", "Infinite"], answer: 3, topic: "Complex Numbers" },
          { id: "S2M15", type: "mcq", text: "The coefficient of $x^4$ in the expansion of $(1 - 2x)^{10}$ is:", options: ["3360", "$-3360$", "1680", "$-1680$"], answer: 0, topic: "Binomial Theorem" },
          { id: "S2M16", type: "mcq", text: "If f(x) = x³ − 6x² + 12x − 3, then f(x) is:", options: ["Strictly increasing on ℝ", "Strictly decreasing on ℝ", "Neither increasing nor decreasing", "Increasing on (0, 2) only"], answer: 0, topic: "Application of Derivatives" },
          { id: "S2M17", type: "mcq", text: "The sum of infinite terms of a GP is 3 and the sum of squares of these terms is 9. The first term is:", options: ["3/2", "2/3", "1", "3/4"], answer: 0, topic: "Sequences & Series" },
          { id: "S2M18", type: "mcq", text: "If the lines x/(1) = y/(2) = z/(3) and x/(k) = y/(2) = z/(1) are perpendicular, then k =", options: ["−5/3", "5/3", "−1", "1"], answer: 0, topic: "3D Geometry" },
          { id: "S2M19", type: "mcq", text: "The derivative of $\\sin^{-1} \\left(\\frac{2x}{1+x^2} \\right)$ with respect to $\\cos^{-1}\\left(\\frac{1-x^2}{1+x^2}\\right)$ is:", options: ["2", "1", "$-1$", "$1/2$"], answer: 1, topic: "Differentiation" },
          { id: "S2M20", type: "mcq", text: "If the eccentricity of the hyperbola x²/a² − y²/b² = 1 is 5/3 and sum of semi-axes is 16, then a² + 4b² =", options: ["140", "160", "180", "200"], answer: 1, topic: "Hyperbola" },
          { id: "S2M21", type: "numerical", text: "$f(x)$ is a 5-degree polynomial that has extremes at $x = \\pm 1$ and $\\lim_{x \\to 0} \\frac{f(x)}{x^3} = 5$, then $f(2) - f(-2)$ is _____.", answer: 32, topic: "Application of Derivatives" },
          { id: "S2M22", type: "numerical", text: "If for 3 ≤ r ≤ 30, ³⁰C₃₀₋ᵣ + 3(³⁰C₃₁₋ᵣ) + 3(³⁰C₃₂₋ᵣ) + ³⁰C₃₃₋ᵣ = ᵐCᵣ, then m equals _____.", answer: 33, topic: "Binomial Theorem" },
          { id: "S2M23", type: "numerical", text: "Let f(x) = x² − 3x + 2. The sum of all values of x satisfying f(f(x)) = 0 is _____.", answer: 6, topic: "Functions" },
          { id: "S2M24", type: "numerical", text: "If the mean of 5 observations is 8 and the variance is 4, then the sum of squares of all 5 observations is _____.", answer: 340, topic: "Statistics" },
          { id: "S2M25", type: "numerical", text: "The number of integral values of x satisfying |x − 3| + |x + 1| < 6 is _____.", answer: 5, topic: "Inequalities" }
        ]
      }
    ]
  }
];

// Default to first paper for backward compatibility
const quizData = allPapers[0];
